from pydantic import BaseModel, Field, PrivateAttr
from KVerse_language_engine.llm_config import AzureChatgpt
from KVerse_blob_storage.storage_utils import download_from_url
from KVerse_database_system.db_utils import retrieve_document
import tiktoken
from queue import Queue
from KVerse_chat_main.utils import ReturnThread

class ToolAgent(BaseModel):
    name: str = Field(..., description="Name of the tool agent")
    description: str = Field(..., description="Description of the tool agent's purpose")

    def __call__(self, *args, **kwargs):
        """
        This method is called when the tool agent is invoked.
        It should be overridden by subclasses to implement specific tool functionality.
        """
        raise NotImplementedError("ToolAgent subclasses must implement the __call__ method.")

class GPTAgent(BaseModel):
    """
    Represents an agent in the KVerse system.
    """
    name: str = Field(..., description="The name of the agent")
    description: str = Field(..., description="A brief description of the agent's purpose")
    version: str = Field(..., description="The version of the agent")
    
    user_id: str|None = Field(default=None, description="The user ID associated with the agent")
    model: str = Field(..., description="The LLM model used by the agent")

    system_prompt: str = Field(..., description="The system prompt for the agent")
    user_prompt: str = Field(..., description="The user prompt for the agent")

    tools: list = Field(default_factory=list, description="List of tools available to the agent")
    tool_choice: str = Field(default="auto", description="The method of tool choice for the agent")

    output_format: str|object = Field(default={"type": "text"}, description="The format of the output generated by the agent")

    web_search_options: dict = Field(default_factory=dict, description="Options for web search capabilities of the agent") 
    
    max_tokens: int = Field(default=4096, description="Maximum number of tokens for the agent's response")
    temperature: float = Field(default=0.7, description="Temperature for response generation")
    top_p: float|None = Field(default=0.95, description="Top-p value for response generation")
    n: int = Field(default=1, description="Number of responses to generate from the agent")
    stream: bool = Field(default=False, description="Whether to stream the response from the agent")
    web_search_options: dict = Field(default_factory=dict, description="Options for web search capabilities of the agent")
    reasoning_effort: str|None = Field(default=None, description="The reasoning effort level for the agent")
    #azure specific fields
    api_version: str = Field(..., description="API version for the agent")
    api_key: str = Field(..., description="API key for accessing the agent's LLM service")
    azure_endpoint: str = Field(..., description="Azure endpoint for the agent's LLM service")
    input_format: dict|None = Field(default = None)
    set_system_prompt: bool = Field(default=False, description="Whether to set the system prompt for the agent")

    maintain_history: bool = Field(default=True, description="Whether to maintain a history of interactions with the agent")
    
    history_length: int = Field(default=5, description="Length of the history to maintain for the agent")
    _llm_client: AzureChatgpt = PrivateAttr()
    _history: dict = PrivateAttr()
    _tokenizer: tiktoken.Encoding = PrivateAttr()
    _num: int = PrivateAttr()
    _tool_agent: ToolAgent = PrivateAttr()

    def __init__(self, child = None, **data):
        super().__init__(**data)
        self._llm_client = AzureChatgpt(
            api_version=self.api_version,
            azure_endpoint=self.azure_endpoint,
            openai_api_key=self.api_key
        )
        if self.maintain_history:
            self._history = dict()
        self._tokenizer = tiktoken.encoding_for_model(self.model) if self.model in ["gpt-4o"] else tiktoken.encoding_for_model("gpt-5")
        self._num = 1
    
    
    def add_attachments(self, attachments: list) -> list:
        """
        Process attachments and return a dict of attachments.
        """
        content = list()
        for attachment in attachments:
            type = attachment.get('mime_type')
            url = attachment.get('blob_url')
            # print("Type Recieved : ", type, type.split('/')[0], type.split('/')[1], type.split('/')[0] == "application", type.split('/')[1]=="octet-stream")
            if type.split('/')[0] == "image" :
                content.append({"type": "image_url", "image_url": {"url": url}})
            elif type.split('/')[0] == "application":
                if type.split('/')[1] in ["pdf", "msword", "json", "vnd.openxmlformats-officedocument.wordprocessingml.document"]:
                    # local_path = download_from_url(url)
                    # file = self._llm_client.attach_file(local_path)
                    # content.append({"type": "input_file", "file_id" : file.id})
                    content.append({"type": "file_url", "file_url": url})
                elif type.split('/')[1] == "octet-stream":
                    content.append({"type": "image_url", "image_url": {"url": url}})
                else:
                    raise ValueError(f"Unsupported application file type: {type}")
            elif type.split('/')[0] == "text":
                if type.split('/')[1] == "plain" or "csv" or "markdown" or "html":
                    # local_path = download_from_url(url)
                    # file = self._llm_client.attach_file(local_path)
                    # content.append({"type": "input_file", "file_id" : file.id})
                    # print("Executing File Text Condition")
                    content.append({"type": "file_url", "file_url": url})
                else:
                    raise ValueError(f"Unsupported text file type: {type}")
            else:
                raise ValueError(f"Unsupported attachment file type: {type}")
        
        print("Content Prepared : ", content)
        return content
    
    def get_history(self, name = None) -> list:
        """
        Returns the history of messages exchanged with the agent.
        """
        if name:
            return [msg for msgs in self._history.values() for msg in msgs if msg['name'] == name] if hasattr(self, 'maintain_history') else []
        return [msg for msgs in self._history.values() for msg in msgs] if hasattr(self, 'maintain_history') else []

    def add_to_history(self, message):
        """
        Adds a message to the agent's history.
        """
        if not self.maintain_history:
            raise ValueError("History is not enabled for this agent.")
        else:
            self._history[self._num] = message
            if self.history_length <= len(self._history):
                    self._history = {k: v for k, v in self._history.items() if k >= self._num - self.history_length} 
            self._num += 1 
            return True, message

    def __call__(self, query, answer_queue = Queue(), temp_history = dict(), tool_call_check = False, usages = [], num = 0, **kwargs) -> tuple[list, dict, dict]:
        """
        Calls the agent with the provided query and additional parameters.
        """
        if self.set_system_prompt:
            document = retrieve_document(collection_name="User_Document",
                                       primary_key=self.user_id)
            if document:
                kwargs["user_system_prompt"] = document[0].get('System_Prompt', "")
            else:
                kwargs["user_system_prompt"] = ""

        kwargs['temperature'] = kwargs.get('temperature', self.temperature)
        kwargs['top_p'] = kwargs.get('top_p', self.top_p)
        kwargs['max_tokens'] = kwargs.get('max_tokens', self.max_tokens)
        kwargs['stream'] = kwargs.get('stream', self.stream)
        if tool_call_check:
            kwargs['n'] = 1
        else:
            kwargs['n'] = kwargs.get('n', self.n)
            temp_history = {n:[{'role': 'user', 'content': query}] for n in range(kwargs['n'])}
        # kwargs['response_format'] = kwargs.get('response_format', self.output_format)
        
        for responses in self._llm_client.get_response(agent=self,
                                                      query=query,
                                                      tool_call_check=tool_call_check,
                                                      **kwargs):
            response_type, response, token_usage_dict, extras, messages = responses # type: ignore
            if not response:
                raise ValueError("No response received from the LLM.")
            if response_type == 'content':
                answer_queue.put([response_type, response])
            elif response_type == 'tool':
                if tool_call_check:
                    raise ValueError("Recursive Tool calls are not supported in this context.")
                futures = dict()

                for num in range(self.n):
                    futures[num] = ReturnThread(
                        target=self.process_tool_call,
                        args=(answer_queue, {0:temp_history[num]}, response[num], extras[num]), # type: ignore
                        kwargs=kwargs
                    )
                    futures[num].start()
                full_content = list()
                for num in range(self.n):
                    temp_content, _temp_history, token_usage_dict_temp = futures[num].join() # type: ignore
                    full_content.extend(temp_content)
                    for key in token_usage_dict_temp[self.model].keys():
                        if key in token_usage_dict.keys():
                            token_usage_dict[key] += token_usage_dict_temp[self.model][key]
                        else:
                            token_usage_dict[key] = token_usage_dict_temp[self.model][key]
                    temp_history[num] = _temp_history[0] # type: ignore
                
            elif response_type == 'stop':
                # print("Received stop signal from the LLM.")
                # print("preprocessing_history: ", temp_history)
                full_content = [content.content for content in response] #type: ignore
                tool_calling_content = [content.tool_calls for content in response if content.tool_calls] #type: ignore
                # print("Tool calling content: ", tool_calling_content, "Full content: ", full_content)
                if tool_calling_content == [None] * len(response) or\
                    tool_calling_content == [""] * len(response) or\
                    tool_calling_content == [] * len(response): #type: ignore
                    for num in range(kwargs['n']):
                        # print(f"Appending response: {response[num]} to temp_history[{num}]")
                        temp_history[num].append(response[num]) # type: ignore
               

                if not token_usage_dict:
                    token_usage_dict = dict()                                                             
                if tool_call_check:
                    token_usage_dict['tool_usage'] = usages
        answer_queue.put(['stop', []])     
        # print(f"Answering Agent completed history: {temp_history}")  
        return full_content, temp_history, {self.model : token_usage_dict}

    def process_tool_call(self, answer_queue, temp_history, response, tool_call, **kwargs, ):
        results, usages =  self._tool_agent(agent = self, tool_call=tool_call) # type: ignore
        temp_history[0].append(response)
        temp_history[0].extend(results)
        if hasattr(self, 'maintain_history'):
            history = self.get_history()
            kwargs['history'] = history # type: ignore
        else:
            kwargs['history'] = []
        kwargs['history'].extend(temp_history[0]) #type: ignore
        print(f"Tool call results: {results}, kwargs: {kwargs}")
        kwargs['usages'] = usages
        return self.__call__(query="", 
                             answer_queue = answer_queue,
                             temp_history=temp_history,
                             tool_call_check=True, 
                             **kwargs)
                





           
        
            

       
